config/routes.rb
Rails.application.routes.draw do

  namespace :wifi do
    # 客户端首次连接wifi，浏览器请求将被重定向到login并携带参数
    # login?gw_address=路由器ip&gw_port=路由器wifidog的端口&gw_id=用户id&mac=用户的mac地址&url=被重定向前用户浏览的地址
    get '/login'  => 'wifi#login',  as: :login
    get '/auth'   => 'wifi#auth',   as: :auth
    get '/ping'   => 'wifi#ping',   as: :ping
    get '/portal' => 'wifi#portal', as: :portal
    get '/gw_message' => 'wifi#gw_message', as: :gw_message
    
    # connect?access_token=xxxxxxx
    get '/connect' => 'wifi#connect', as: :connect
    
    post '/control86' => 'wifi#control86', as: :control86
  end
  
  # 商家后台
  namespace :portal, path: '' do
    root 'home#index'
    resources :merchants,     path: 'shop'
    resources :access_points, path: 'ap'
    resources :wifi_auth_configs, path: 'auth_config', only: [:update]
    get 'auth_config/manage' => 'wifi_auth_configs#edit', as: :manage_auth_config
  end
  
  mount RedactorRails::Engine => '/redactor_rails'
  
  # 网页文档
  resources :pages, path: :p, only: [:show]
  
  # 管理后台系统登录
  devise_for :admins, ActiveAdmin::Devise.config
  # 后台系统路由
  ActiveAdmin.routes(self)
  
  # 会员系统登录
  devise_for :users, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
  }
  
  # 队列后台管理
  require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  authenticate :admin do
    mount Sidekiq::Web => 'sidekiq'
  end
  
  # API 文档
  mount GrapeSwaggerRails::Engine => '/apidoc'
  
  # API 路由
  mount API::Dispatch => '/api'
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  validates :name, :address, presence: true
  
  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  
  before_create :generate_unique_id
  def generate_unique_id
    begin
      n = rand(10)
      if n == 0
        n = 8
      end
      self.merch_id = (n.to_s + SecureRandom.random_number.to_s[2..6]).to_i
    end while self.class.exists?(:merch_id => merch_id)
  end
end

app/controllers/portal/access_points_controller.rb
class Portal::AccessPointsController < Portal::ApplicationController
  before_action :set_ap, only: [:show, :edit, :destroy]
  
  def index
    @page_header = "设备列表"
    @action = new_portal_access_point_path
    @access_points = AccessPoint.order('id desc').paginate page: params[:page], per_page: 30
  end
  
  # def show
  #   @page_header = "产品详情"
  # end
  def show
    @page_header = "设备详情"
  end
  
  def new
    @page_header = "新建设备"
    @access_point = AccessPoint.new
  end
  
  def create
    @access_point = AccessPoint.new(access_point_params)
    
    @shop = Merchant.find_by(id: params[:access_point][:merchant_id])
    if @shop.blank? or @shop.owner.blank? or @shop.owner != current_user
      flash[:error] = '非法操作'
      redirect_to new_portal_access_point_path
      return
    end
    
    if @access_point.save
      flash[:success] = '创建成功'
      redirect_to portal_access_points_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新设备"
  end
  
  def update
    @access_point = AccessPoint.find(params[:id])
    if @access_point.merchant.blank? or @access_point.merchant.owner.blank? or @access_point.merchant.owner != current_user
      flash[:error] = '非法操作'
      redirect_to portal_access_points_url
      return
    end
    if @access_point.update(access_point_params)
      flash[:success] = '更新成功'
      redirect_to portal_access_points_url
    else
      render :edit
    end
  end
  
  def destroy
    @access_point.destroy
    flash[:success] = '删除成功'
    redirect_to portal_access_points_url
  end
  
  private
  
  def set_ap
    @access_point = AccessPoint.find_by(ap_id: params[:id])
    if @access_point.blank?
      flash[:error] = '没找到设备'
      rediret_to portal_access_points_url
      return
    end
    
    if @access_point.merchant.blank? or @access_point.merchant.owner != current_user
      flash[:error] = '非法操作'
      rediret_to portal_access_points_url
      return
    end
  end
  
  def access_point_params
    params.require(:access_point).permit(:ssid, :gw_mac, :gw_address, :gw_port, :merchant_id)
  end
end

app/controllers/portal/application_controller.rb
class Portal::ApplicationController < ApplicationController
  # include Pundit
  
  layout 'portal'
  
  before_filter :require_user
  before_filter :check_user
  # before_filter :require_member
  # before_filter :check_member
  # before_filter :check_more_profile
  
  # rescue_from Pundit::NotAuthorizedError, with: :unauthorized
  
  private
  
  # alias_method :pundit_user, :current_member
  
  # def unauthorized
  #   redirect_to request.referrer || portal_root_path, alert: '没有权限执行！'
  # end
  
end

app/controllers/portal/customers_controller.rb
class Portal::CustomersController < Portal::ApplicationController
  before_action :set_customer, only: [:show, :edit, :destroy]
  
  def index
    authorize Customer
    @page_header = "客户列表"
    @action = new_portal_customer_path
    @customers = policy_scope(Customer).paginate page: params[:page], per_page: 30
  end
  
  def show
    @page_header = "客户详情"
  end
  
  def new
    @page_header = "新建客户"
    @customer = Customer.new
    authorize @customer
  end
  
  def create
    @customer = Customer.new(customer_params)
    authorize @customer
    @customer.owner_id = current_member.account.id
    if @customer.save
      flash[:success] = '创建成功'
      redirect_to portal_customers_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新客户资料"
  end
  
  def update
    @customer = Customer.find_by(owner_id: current_member.account.id, id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
    
    if @customer.update(customer_params)
      flash[:success] = '更新成功'
      redirect_to portal_customers_url
    else
      render :edit
    end
  end
  
  def destroy
    @customer.destroy
    flash[:success] = '删除成功'
    redirect_to portal_customers_url
  end
  
  private
  def set_customer    
    @customer = Customer.find_by(owner_id: current_member.account.id, o_id: params[:id])
    
    if @customer.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_customers_url
      return
    end
    
    authorize @customer
  end
  
  def customer_params
    params.require(:customer).permit(:avatar, :nickname, :realname, :mobile, :address)
  end
end

app/controllers/portal/home_controller.rb
class Portal::HomeController < Portal::ApplicationController
  
  def index
    @page_header = "控制面板"
  end
end

app/controllers/portal/merchants_controller.rb
class Portal::MerchantsController < Portal::ApplicationController
  # before_action :set_merchant, only: [:show, :edit, :destroy]
  
  def index
    @page_header = "门店列表"
    @action = new_portal_merchant_path
    @merchants = Merchant.order('id desc').paginate page: params[:page], per_page: 30
  end
  
  # def show
  #   @page_header = "产品详情"
  # end
  
  def new
    @page_header = "新建门店"
    @merchant = Merchant.new
  end
  
  def create
    @merchant = Merchant.new(merchant_params)
    @merchant.owner_id = current_user.id
    if @merchant.save
      flash[:success] = '创建成功'
      redirect_to portal_merchants_url
    else
      # puts @product.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新门店"
    @merchant = current_user.merchants.find_by(merch_id: params[:id])
    if @merchant.blank?
      flash[:error] = '门店不存在'
      rediret_to portal_merchants_url
      return
    end
  end
  
  def update
    @merchant = current_user.merchants.find(params[:id])
    if @merchant.update(merchant_params)
      flash[:success] = '更新成功'
      redirect_to portal_merchants_url
    else
      render :edit
    end
  end
  
  def destroy
    @merchant = current_user.merchants.find_by(merch_id: params[:id])
    
    if @merchant.blank?
      flash[:error] = '门店不存在'
      rediret_to portal_merchants_url
      return
    end
    @merchant.destroy
    flash[:success] = '删除成功'
    redirect_to portal_merchants_url
  end
  
  private
  
  def merchant_params
    params.require(:merchant).permit(:name, :address, :mobile, :memo)
  end
end

app/controllers/portal/roles_controller.rb
class Portal::RolesController < Portal::ApplicationController
  
  def index
    @page_header = "角色列表"
    authorize Role
    @action = new_portal_role_path
    @roles = policy_scope(Role).paginate page: params[:page], per_page: 30
  end
  
  def new
    @page_header = "新建产品"
    @role = Role.new
    authorize @role
  end
  
  def create
    @role = Role.new(role_params)
    authorize @role
    @role.owner_id = current_member.id
    puts @role.name
    if @role.save
      flash[:success] = '创建成功'
      redirect_to portal_roles_url
    else
      # flash.now.alert = @role.errors.full_messages.join(',')
      # puts @role.errors.full_messages
      render :new
    end
  end
  
  def edit
    @page_header = "更新角色"
    
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    # @role = Role.find(params[:id])
    authorize @role
  end
  
  def update
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    if @role.update(role_params)
      flash[:success] = '更新成功'
      redirect_to portal_roles_url
    else
      render :edit
    end
  end
  
  def destroy
    # @role = Role.find(params[:id])
    @role = Role.find_by(id: params[:id], owner_id: current_member.id)
    if @role.blank?
      flash[:alert] = '记录不存在'
      redirect_to portal_roles_path
      return
    end
    
    authorize @role
    @role.destroy
    redirect_to portal_roles_url
  end
  
  private
  def role_params
    role_params = params.require(:role).permit(:name, permissions: [])
    role_params[:permissions] = build_permissions(role_params[:permissions] || [])
    role_params
  end
  
  def build_permissions(permissions)
    # puts permissions
    parse_permissions(permissions).collect do |permission|
      if @role.nil?
        Permission.new(permission)
      else
        @role.permissions.find_or_initialize_by(permission)
      end
    end
  end
  
  def parse_permissions(permissions)
    permissions.collect do |permission|
      action, resource = permission.split('#', 2)
      { action: action, resource: resource }
    end
  end
  
end

app/controllers/portal/wifi_auth_configs_controller.rb
class Portal::WifiAuthConfigsController < Portal::ApplicationController
  
  def edit
    @page_header = '认证配置'
    @config = current_user.auth_config
    if @config.blank?
      @config = WifiAuthConfig.create!(user_id: current_user.id)
    end
  end
  
  def update
     @config = current_user.auth_config
     if @config.update(config_params)
       flash[:success] = '保存成功'
       redirect_to portal_manage_auth_config_path
     else
       render :edit
     end
  end
  
  private
  def config_params
    params.require(:wifi_auth_config).permit(:auth_type, :wifi_length, :auto_jump, :countdown, :auth_click_button, :https_auth_support, :allow_websites, :allow_macs, :not_allow_macs)
  end
  
end

app/views/portal/merchants/_form.html.erb
<div class="x_panel">
  <div class="x_content">
    <br />
    
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    
        <%= simple_form_for([:portal, @merchant], html: { class: 'form-horizontal form-label-left', id: 'product_form' },
          wrapper: :horizontal_form,
          wrapper_mappings: {
            check_boxes: :horizontal_radio_and_checkboxes,
            radio_buttons: :horizontal_radio_and_checkboxes,
            file: :horizontal_file_input,
            boolean: :horizontal_boolean
          }) do |f| %>
            <%= f.input :name %>
            <%= f.input :address %>
            <%= f.input :mobile %>
            <%= f.input :memo %>
            <div class="form-group">
              <div class="col-md-6 col-md-offset-3">
                <%= link_to '取消', :back, class: "btn btn-primary" %>
                <button type="submit" class="btn btn-success"><%= f.object.new_record? ? "新建门店" : "更新门店" %></button>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/portal/merchants/_merchant.html.erb
<tr>
  <td><%= merchant.name %></td>
  <td><%= merchant.address %></td>
  <td><%= merchant.mobile.blank? ? '-' : merchant.mobile %></td>
  <td><%= merchant.memo %></td>
  <td>
    <%= link_to '编辑', edit_portal_merchant_path(merchant.merch_id), class: 'btn btn-sm btn-default' %>
    <%= link_to '删除', portal_merchant_path(merchant.merch_id), method: :delete,  data: { confirm: '您确定吗？' },class: 'btn btn-sm btn-danger' %>
  </td>
</tr>

app/views/portal/merchants/edit.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>修改门店</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>

app/views/portal/merchants/index.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>门店列表</h3>
  </div>

  <div class="title_right">
    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="输入门店名称">
        <span class="input-group-btn">
          <button class="btn btn-default" type="button">搜索</button>
        </span>
      </div>
    </div>
  </div>
</div>

<div class="clearfix"></div>

<% if @merchants.empty? %>
<div class="x_panel">
  <div class="x_content">
    <div class="no-results"><无数据显示><br /><%= link_to '新建门店', @action, class: 'btn btn-primary' %></div>
  </div>
</div>
<% else %>            
<div class="x_panel">
  <div class="x_content">
    <div class="content-list">
      <table class="table table-striped table-hover">
        <thead>
          <tr>
            <th>名称</th>
            <th>地址</th>
            <th>联系电话</th>
            <th>备注</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <%= render @merchants %>
        </tbody>
      </table>
    </div>
  </div>
  <div style="text-align: center;"><%= will_paginate @merchants, renderer: BootstrapPagination::Rails %></div>
</div>

<% end %>

app/views/portal/merchants/new.html.erb
<div class="page-title">
  <div class="title_left">
    <h3>新建门店</h3>
  </div>
</div>

<div class="clearfix"></div>

<%= render 'form' %>