config/routes.rb
Rails.application.routes.draw do

  namespace :wifi do
    # 客户端首次连接wifi，浏览器请求将被重定向到login并携带参数
    # login?gw_address=路由器ip&gw_port=路由器wifidog的端口&gw_id=用户id&mac=用户的mac地址&url=被重定向前用户浏览的地址
    get '/login'  => 'wifi#login',  as: :login
    get '/auth'   => 'wifi#auth',   as: :auth
    get '/ping'   => 'wifi#ping',   as: :ping
    get '/portal' => 'wifi#portal', as: :portal
    get '/gw_message' => 'wifi#gw_message', as: :gw_message
    
    # connect?access_token=xxxxxxx
    get '/connect' => 'wifi#connect', as: :connect
    
    post '/control86' => 'wifi#control86', as: :control86
  end
  
  # 商家后台
  namespace :portal, path: '' do
    root 'home#index'
    resources :merchants,     path: 'shop'
    resources :access_points, path: 'ap'
    resources :wifi_auth_configs, path: 'auth_config', only: [:update]
    get 'auth_config/manage' => 'wifi_auth_configs#edit', as: :manage_auth_config
  end
  
  mount RedactorRails::Engine => '/redactor_rails'
  
  # 网页文档
  resources :pages, path: :p, only: [:show]
  
  # 管理后台系统登录
  devise_for :admins, ActiveAdmin::Devise.config
  # 后台系统路由
  ActiveAdmin.routes(self)
  
  # 会员系统登录
  devise_for :users, path: "account", controllers: {
    registrations: :account,
    sessions: :sessions,
  }
  
  # 队列后台管理
  require 'sidekiq/web'
  # require 'sidekiq/cron/web'
  authenticate :admin do
    mount Sidekiq::Web => 'sidekiq'
  end
  
  # API 文档
  mount GrapeSwaggerRails::Engine => '/apidoc'
  
  # API 路由
  mount API::Dispatch => '/api'
end

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<![endif]-->

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render_page_title %>
  <meta charset='utf-8' />
  <meta name="keywords" content="<%= @meta_keywords %>" />
  <meta name="description" content="<%= @meta_description %>" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!--meta name="viewport" content="width=device-width, initial-scale=1"-->
  <!-- non responsive -->
  <%= stylesheet_link_tag  'front', 'data-turbolinks-track' => true %>
  
  <link rel="shortcut icon" href="<%= asset_path("favicon.ico") %>" />
  
  <%= yield :styles %>
  
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body>    
  <div class="account-header">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="brand pull-left" href="/">
            <%= image_tag 'logo.png', class: 'logo', alt: '得益无线平台' %>
          </a>
        </div>
        <ul class="nav navbar-nav navbar-right link">
          <li>
            <% if controller_name == 'sessions' and action_name == 'new' %>
            <a href="<%= new_user_registration_path %>">注册</a>
            <% elsif controller_name == 'account' and action_name == 'new' %>
            <a href="<%= new_user_session_path %>">登录</a>
            <% end %>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  
  <div class="container">
    <%= yield %>
  </div>
  
  <div class="footer">
    <div class="copyright">
      <small>
          版权所有 &copy; <%= Time.now.year %> 得益 保留所有权利.蜀ICP备14031323号
        </small>
    </div>
  </div>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= yield :scripts %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8' />
  <meta name="keywords" content="<%= @meta_keywords %>" />
  <meta name="description" content="<%= @meta_description %>" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="shortcut icon" href="<%= asset_path("favicon.png") %>" />
  
  <%= stylesheet_link_tag    'front', media: 'all' %>
  <%= yield :styles %>
  <%= csrf_meta_tags %>
  
  <%= render 'layouts/shim' %>
  
</head>
<body>

  <div class="account-header">
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="brand pull-left" href="http://yy.afterwind.cn">
            <%= image_tag 'logo.png', class: 'logo', alt: '云影' %>
          </a>
          <span class="action"><%= @action %></span>
        </div>
        <ul class="nav navbar-nav link">
          <li><a href="/">首页</a></li>
          <li><a href="/">产品</a></li>
          <li><a href="/">价格</a></li>
          <li><a href="/">关于</a></li>
        </ul>
        
        <ul class="nav navbar-nav navbar-right link">
          <li><a href="<%= new_member_session_path %>">登录</a></li>
          <li><a href="<%= new_member_registration_path %>">注册</a></li>
        </ul>
      </div>
    </nav>
  </div>

  <div class="container">
    <%= yield %>
  </div>

  <div class="footer">
    <div class="copyright">
      <small>
          版权所有 &copy; <%= Time.now.year %> 云影 保留所有权利.蜀ICP备14031323号
        </small>
    </div>
  </div>

<%= javascript_include_tag 'application' %>
<%= yield :scripts %>
</body>
</html>

app/views/layouts/portal.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= render_page_title %>
  <!--meta name="viewport" content="width=device-width, initial-scale=1"-->
  <!-- non responsive -->
  <%= stylesheet_link_tag  'portal', 'data-turbolinks-track' => true %>
  
  <link rel="shortcut icon" href="<%= asset_path("favicon.ico") %>" />
  
  <%= yield :styles %>
  
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body class="nav-md">
  
  <div class="container body">
    <div class="main_container">
      
      <div class="col-md-3 left_col">
        <div class="left_col scroll-view">
          <div class="navbar nav_title" style="border: 0;">
            <a href="<%= portal_root_path %>" class="site_title"><%= image_tag 'favicon.ico', class: 'img-circle' %></i> <span>得益WIFI</span></a>
          </div>

          <div class="clearfix"></div>

          <!-- menu profile quick info -->
          <div class="profile clearfix">
            <div class="profile_pic">
              <%= member_avatar_tag(current_user, :large, 'img-circle profile_img') %>
            </div>
            <div class="profile_info">
              <span>您好,</span>
              <h2><%= current_user.uid %></h2>
            </div>
          </div>
          <!-- /menu profile quick info -->

          <br />

          <!-- sidebar menu -->
          <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
              <h3>功能</h3>
              <ul class="nav side-menu">
                <li><a href="<%= portal_root_path %>"><i class="fa fa-home"></i> 控制面板 <span class="fa fa-chevron-right"></span></a>
                </li>
                <li><a><i class="fa fa-table"></i> 门店管理 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="<%= new_portal_merchant_path %>">新建门店</a></li>
                    <li><a href="<%= portal_merchants_path %>">门店列表</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-table"></i> 设备管理 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="<%= new_portal_access_point_path %>">新建设备</a></li>
                    <li><a href="<%= portal_access_points_path %>">设备列表</a></li>
                  </ul>
                </li>
                <li><a><i class="fa fa-clone"></i> 页面管理 <span class="fa fa-chevron-down"></span></a>
                  <ul class="nav child_menu">
                    <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                    <li><a href="fixed_footer.html">Fixed Footer</a></li>
                  </ul>
                </li>
                <li><a href="<%= portal_manage_auth_config_path %>"><i class="fa fa-clone"></i> 认证管理 <span class="fa fa-chevron-right"></span></a>
                </li>
              </ul>
            </div>

          </div>
          <!-- /sidebar menu -->

          <!-- /menu footer buttons -->
          <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="设置">
              <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="个人资料">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="帮助">
              <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="退出登录" href="login.html">
              <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
          </div>
          <!-- /menu footer buttons -->
        </div>
      </div>

      <!-- top navigation -->
      <div class="top_nav">
        <div class="nav_menu">
          <nav>
            <div class="nav toggle">
              <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
              <li class="">
                <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                  <%= member_avatar_tag(current_user, :small) %>
                  <%= current_user.uid %>
                  <span class=" fa fa-angle-down"></span>
                </a>
                <ul class="dropdown-menu dropdown-usermenu pull-right">
                  <li><a href="javascript:;">个人资料</a></li>
                  <!--li>
                    <a href="javascript:;">
                      <span class="badge bg-red pull-right">50%</span>
                      <span>设置</span>
                    </a>
                  </li-->
                  <li><a href="javascript:;">修改密码</a></li>
                  <li><a href="/account/sign_out" data-method="delete"><i class="fa fa-sign-out pull-right"></i>退出登录</a></li>
                </ul>
              </li>

              <!--li role="presentation" class="dropdown">
                <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                  <i class="fa fa-envelope-o"></i>
                  <span class="badge bg-green">6</span>
                </a>
                <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                  <li>
                    <a>
                      <span class="image"><%= image_tag 'avatar/small.png' %></span>
                      <span>
                        <span>John Smith</span>
                        <span class="time">3 mins ago</span>
                      </span>
                      <span class="message">
                        Film festivals used to be do-or-die moments for movie makers. They were where...
                      </span>
                    </a>
                  </li>
                  <li>
                    <div class="text-center">
                      <a>
                        <strong>See All Alerts</strong>
                        <i class="fa fa-angle-right"></i>
                      </a>
                    </div>
                  </li>
                </ul>
              </li -->
            </ul>
          </nav>
        </div>
      </div>
      <!-- /top navigation -->
      
      <!-- page content -->
      <div class="right_col" role="main">
        <%= notice_message %>
        
        <%= yield %>
      </div>
      <!-- page content -->
      
      <!-- footer content -->
      <footer>
        <div class="pull-right">
          版权所有 &copy; <%= Time.now.year %> <a href="http://cloud.deyiwifi.com" target="_blank">得益WIFI</a> 保留所有权利.蜀ICP备14031323号
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
      
    </div>
  </div>
  
  <%= javascript_include_tag 'portal', 'data-turbolinks-track' => true %>
  <%= yield :scripts %>
</body>
</html>

app/views/layouts/wechat.xml.erb
<xml>
  <ToUserName><![CDATA[<%= wechat_xml.from_user %>]]></ToUserName>
  <FromUserName><![CDATA[<%= wechat_xml.to_user %>]]></FromUserName>
  <CreateTime><%= Time.now.to_i %></CreateTime>
  <%= yield %>
  <FuncFlag>0</FuncFlag>
</xml>